name: Checkout then build AdvancedInstaller
on: [push]
jobs:
   hello_world_job:
      runs-on: localDH-smsclient
      name: Checkout then build AdvancedInstaller
      steps:
         - name: Checkout - pull git repo
           uses: actions/checkout@v2

         - name: Powershell get data to build
           run: .\dist\create_option_advanced_installer_build.ps1
           shell: powershell

         # Thá»­ check in3
         #  - name: Run nodejs
         #    run: node index.js
